# Dockerfile
# Build stage to download and prepare the application
# ------------------------------------------------------
FROM python:3.13-slim AS builder
WORKDIR /app

# Install necessary packages
RUN apt-get update && apt-get install -y \
 gzip \
 curl \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Download with checksum verification (retry up to 3 times)
# If checksum fails after 3 attempts, abort the build
# -eux: exit on error and print commands
RUN set -eux; \
    url="https://osf.io/download/p84gq/?view_only=9539cd4703fe42c09e8fb1cf0567cc6b"; \
    sha_expected="27d7acac07deee9d9bdf963ed24090a97dd23f1aa935e3731a7943fc39560cf8"; \
    for i in $(seq 1 3); do \
        echo "Attempt $i: downloading SENCORE_08_11_2025.db.gz"; \
        # Download the file: -fsSL -> fail silently on server errors,no bars,show errors, use redirects
        curl -fsSL "$url" -o SENCORE_08_11_2025.db.gz; \
        # Save downloaded file's checksum
        sha_actual=$(sha256sum SENCORE_08_11_2025.db.gz | awk '{print $1}'); \
        # Compare checksums
        if [ "$sha_actual" = "$sha_expected" ]; then \
            echo "Checksum OK"; \
            break; \
        else \
            echo "Checksum mismatch (got $sha_actual, expected $sha_expected)"; \
            rm -f SENCORE_08_11_2025.db.gz; \
            if [ "$i" -eq 3 ]; then \
                echo "Download failed after 3 attempts (checksum mismatch). Aborting build."; \
                exit 1; \
            fi; \
            # Exponential backoff before retrying in case server is busy
            sleep $((i*5)); \
        fi; \
    done
# Decompress the database file and download/install dependencies
RUN gzip -d SENCORE_08_11_2025.db.gz
COPY app.py requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


# Final stage, create a minimal image
# ------------------------------------
FROM python:3.13-slim AS final
WORKDIR /app
COPY --from=builder /app/app.py /app/SENCORE_08_11_2025.db ./
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin


EXPOSE 8501
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--theme.base=dark", "--browser.gatherUsageStats=false", "--global.showWarningOnDirectExecution=true", "--server.headless=true", "--server.fileWatcherType='none'", "--server.showEmailPrompt=false", "--client.toolbarMode=minimal"]